# -*- coding: utf-8 -*-
"""praktikum05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHHyB4hBU9RXDU_pXpQvq6TqJIqJ0YIg
"""

namakendaraan = "vario, beat, civic, pajero"
jeniskendaraan = "motor, mobil"
cckendaraann = 150, 160, 1500
warnakendaraan = "merah,hitam"
rodakendaraan = 2,4

datakendaraan = [namakendaraan, jeniskendaraan,cckendaraann,
                  warnakendaraan, rodakendaraan]

print(datakendaraan)

hargakendaraan = 60000
tipekendaraan = "metic"

datakendaraan.append(hargakendaraan)
datakendaraan.append(tipekendaraan)
print(datakendaraan)

merekkendaraan = "honda"
datakendaraan.insert(2, merekkendaraan)
print(datakendaraan)

pilihan = input("""
silahkan pilih luas yang dibutuhkan
===================================
1. luas persegi
2. luas lingkaran
3. luas segitiga
===================================
kirimkan hanya angka saja
jawaban = """)

match pilihan :
  case "1":
    sisi = int(input("sisi ="))
    luas = sisi * sisi

    print(f"luas persegi dengan sisi {sisi} adalah {luas}")
    # luas persegi
  case "2":
    # luas lingkaran
    # Math.pi*jari_jari**2
    jari_jari = int(input("jari_jari ="))
    luas = 3.14*jari_jari**2
    print(f"luas lingkaran dengan jari_jari {jari_jari} adalah {luas}")

  case "3":
    # luas segitiga
    # (alas * tinggi)/2
    alas = float(input("masukan panjang alas segitiga"))
    tinggi = float(input("masukan tinggi segitiga"))
    luas = (alas * tinggi)/2
    print(f"luas segitiga adalah: {luas:.2f}")